### ISSUE TITLE
Request release

### ISSUE THREAD

**Issue by songsammy** [UniBreakfast/believable-random-data-generator#2]
I would like to use jsdelivr as my CDN.
This requires a release. Jsdelivr will work with only releases.
So it would be very kind of you to make a release.

**Comment by UniBreakfast** [comment]
Well, I pressed some random buttons... I hope it helps. Please let me know in any case.

**Comment by songsammy** [comment]
It works! Thanks a lot.
https://cdn.jsdelivr.net/gh/UniBreakfast/believable-random-data-generator@1.1.1/stuff.js

Or even
https://cdn.jsdelivr.net/gh/UniBreakfast/believable-random-data-generator@1.1.1/stuff.min.js
And here's the directory list:

https://cdn.jsdelivr.net/gh/UniBreakfast/believable-random-data-generator@1.1.1/stuff.js

**Comment by UniBreakfast** [comment]
Happy to hear that! Thanks.
